num1 = int(input("introduce el primer numero: "))
num2 = int (input("introduce el segundo numero: "))
num3 = int(input("Introduce el tercer numero: "))
promedio = (num1 + num2 + num3)
print(f" El promedio es: {promedio}")